[versions]
android = "7.0.4"
kotlin = "1.6.21"

[libraries]
android-toolsBuild-gradle = { module = "com.android.tools.build:gradle", version.ref = "android" }
jetbrains-kotlin-kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
